version: '3.5'

services:
  redis:
    image: redis
    hostname: redis
    container_name: redis
    expose:
    - "6379"
    ports:
    - "6379:6379"
    restart: always

  redis-commander:
    hostname: redis-commander
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    restart: always
